=== OmkarLolage21/Kestrel/threat-enrichment/schemas/enriched_event.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["event_id", "agent_id", "event_type", "payload", "enrichment", "timestamp"],
  "properties": {
    "event_id": { "type": "string" },
    "agent_id": { "type": "string" },
    "event_type": { "type": "string" },
    "payload": { "type": "object" },
    "enrichment": {
      "type": "object",
      "properties": {
        "iocs": { "type": "object" },
        "yara_hits": { "type": "array", "items": { "type": "string" } },
        "reputation": { "type": "object" },
        "geoip": { "type": "object" },
        "threat_score": { "type": "number" }
      }
    },
    "timestamp": { "type": "string", "format": "date-time" }
  }
}

=== OmkarLolage21/Kestrel/threat-enrichment/schemas/sample_enriched_events/file.json
{
  "event_id": "b6844d40-300d-9776-8402-476c02be2689",
  "agent_id": "windows-agent-001",
  "event_type": "file",
  "payload": {
    "event_type": "create",
    "file_hash": "96ad1146eb96877eab5942ae0736b82d8b5e2039a80d3d6932665c1a4c87dcf7",
    "file_name": "__PSScriptPolicyTest_p0wx5bdw.rwh.ps1",
    "file_path": "C:\\Users\\parth\\AppData\\Local\\Temp\\__PSScriptPolicyTest_p0wx5bdw.rwh.ps1",
    "file_size": 60,
    "file_type": ".ps1",
    "process_id": 0,
    "process_name": "",
    "severity": "medium"
  },
  "enrichment": {
    "ioc_matches": [
      "otx_pulses"
    ],
    "reputation": {
      "vt": {
        "positives": 0,
        "total": 76
      },
      "otx": {
        "pulses": 50
      }
    },
    "yara_hits": [
      "PowerShell_Suspicious_Temp_File",
      "PowerShell_Suspicious_Temp_Execution"
    ],
    "geoip": {},
    "threat_score": 60.0
  },
  "timestamp": "2025-10-28T12:21:00+05:30"
}

=== OmkarLolage21/Kestrel/threat-enrichment/schemas/sample_enriched_events/process.json
{
  "event_id": "5ffd2623-34d1-46c4-180f-37c3576a7222",
  "agent_id": "windows-agent-001",
  "event_type": "process",
  "payload": {
    "command_line": "",
    "cpu_usage": 0,
    "end_time": "2025-10-28T12:20:20.8090238+05:30",
    "event_type": "stop",
    "executable_path": "",
    "hash": "",
    "memory_usage": 0,
    "parent_process_id": 0,
    "process_id": 11812,
    "process_name": "",
    "severity": "low",
    "signature": "",
    "start_time": "0001-01-01T00:00:00Z",
    "username": ""
  },
  "enrichment": {
    "ioc_matches": [
      "system_parent"
    ],
    "reputation": {
      "vt": {}
    },
    "yara_hits": [],
    "geoip": {},
    "threat_score": 10.0
  },
  "timestamp": "2025-10-28T12:20:20+05:30"
}

=== OmkarLolage21/Kestrel/threat-enrichment/schemas/sample_enriched_events/network.json
{
  "event_id": "dc6ccf7c-40b2-895a-3cbf-b57b8355041f",
  "agent_id": "windows-agent-001",
  "event_type": "network",
  "payload": {
    "bytes_received": 0,
    "bytes_sent": 0,
    "connection_id": "192.168.56.1:1900-:0-UDP",
    "event_type": "connect",
    "local_ip": "192.168.56.1",
    "local_port": 1900,
    "process_id": 6368,
    "process_name": "",
    "protocol": "UDP",
    "remote_ip": "",
    "remote_port": 0,
    "severity": "low"
  },
  "enrichment": {
    "ioc_matches": [],
    "reputation": {
      "otx": {}
    },
    "yara_hits": [],
    "geoip": {},
    "threat_score": 0.0
  },
  "timestamp": "2025-10-28T12:20:13+05:30"
}

=== OmkarLolage21/Kestrel/threat-enrichment/schemas/sample_enriched_events/system.json
{
  "event_id": "2d3d54f3-896a-4bdd-100b-3a10d8c38592",
  "agent_id": "windows-agent-001",
  "event_type": "system",
  "payload": {
    "architecture": "amd64",
    "available_memory": 5528776704,
    "cpu_count": 4,
    "cpu_usage": 36.49017467248908,
    "disk_usage": 71.7140073864804,
    "hostname": "Parths-Laptop",
    "os_version": "windows amd64",
    "total_memory": 16910159872,
    "uptime": 12135
  },
  "enrichment": {
    "ioc_matches": [],
    "reputation": {},
    "yara_hits": [],
    "geoip": {},
    "threat_score": 0.0
  },
  "timestamp": "2025-10-28T12:18:38+05:30"
}
